name: Deploy Image to GHCR


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './harsedoodle'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.CR_PAT}}

          - name: 'Build Image'
            run: |
              docker build . --tag ghcr.io/nickjgniklu/harsedoodle:latest
              docker push ghcr.io/nickjgniklu/harsedoodle:latest
